### ISSUE TITLE
Support for screen sharing

### ISSUE THREAD

**Issue by lesinigo** [zoom/videosdk-ui-toolkit-ios#3]
The web UI Toolkit does support screen sharing, is it possible to get the same feature also on the iOS UI Toolkit?

**Comment by BoonJunTan** [comment]
Hi @lesinigo,

I appreciate your interest. We are currently developing the screen-sharing feature for the iOS UI Toolkit and should be releasing it in the next update (Sep). I will update this thread again once it is made available.

Cheers.

**Comment by BoonJunTan** [comment]
@lesinigo We have launched screen sharing feature in the latest UI toolkit version - v1.12.10-1.
